//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diot.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving your selections....
        /// </summary>
        internal static string AddingMovies {
            get {
                return ResourceManager.GetString("AddingMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected movies.
        /// </summary>
        internal static string AddSelectedMovies {
            get {
                return ResourceManager.GetString("AddSelectedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0}?.
        /// </summary>
        internal static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete title?.
        /// </summary>
        internal static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Title.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom format....
        /// </summary>
        internal static string EnterCustomFormat {
            get {
                return ResourceManager.GetString("EnterCustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select owned formats for\n{0}.
        /// </summary>
        internal static string FormatSelectionInstructions {
            get {
                return ResourceManager.GetString("FormatSelectionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like something went wrong. Please try again..
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... something went wrong.
        /// </summary>
        internal static string GenericErrorTitle {
            get {
                return ResourceManager.GetString("GenericErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading movie details....
        /// </summary>
        internal static string LoadingMovieDetails {
            get {
                return ResourceManager.GetString("LoadingMovieDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Details.
        /// </summary>
        internal static string MovieDetails {
            get {
                return ResourceManager.GetString("MovieDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie title....
        /// </summary>
        internal static string MovieTitle {
            get {
                return ResourceManager.GetString("MovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation error.
        /// </summary>
        internal static string NavigationError {
            get {
                return ResourceManager.GetString("NavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhh... Something went wrong. Try again..
        /// </summary>
        internal static string NavigationErrorMessage {
            get {
                return ResourceManager.GetString("NavigationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cover image found.
        /// </summary>
        internal static string NoCoverImageFound {
            get {
                return ResourceManager.GetString("NoCoverImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies.
        /// </summary>
        internal static string NoMovies {
            get {
                return ResourceManager.GetString("NoMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap &quot;.
        /// </summary>
        internal static string NoMoviesInstructions1 {
            get {
                return ResourceManager.GetString("NoMoviesInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; in the toolbar to add a movie.
        /// </summary>
        internal static string NoMoviesInstructions2 {
            get {
                return ResourceManager.GetString("NoMoviesInstructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network connection.
        /// </summary>
        internal static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for a movie requires an internet connection. Please try again..
        /// </summary>
        internal static string NoNetworkConnectionMessage {
            get {
                return ResourceManager.GetString("NoNetworkConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results.
        /// </summary>
        internal static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for &quot;{0}&quot; found..
        /// </summary>
        internal static string NoSearchResultsMessage {
            get {
                return ResourceManager.GetString("NoSearchResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other: .
        /// </summary>
        internal static string OtherColon {
            get {
                return ResourceManager.GetString("OtherColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found possible matches. Getting details on each....
        /// </summary>
        internal static string PossibleMatchesText {
            get {
                return ResourceManager.GetString("PossibleMatchesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by title....
        /// </summary>
        internal static string SearchByTitle {
            get {
                return ResourceManager.GetString("SearchByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for {0}....
        /// </summary>
        internal static string SearchingMovie {
            get {
                return ResourceManager.GetString("SearchingMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starring.
        /// </summary>
        internal static string Starring {
            get {
                return ResourceManager.GetString("Starring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
